name: gitartwork from a contribution graph

on: 
  push:
  schedule:
    # Runs automatically every 24 hours to keep the graph updated
    - cron: '* */24 * * *' 

jobs:
  build:
    name: Make gitartwork SVG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jasineri/gitartwork@v1
        with:
           # The username's contribution graph to use
           user_name: ar-yan9
           # The text you want it to draw (Keep it short, e.g., 3-7 letters)
           text: ARYAN
      - uses: jasineri/simple-push-action@v1
